---
name: module3_task2

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  container_test_job:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Install missing tools
        run: |
          cd module3_task1
          chmod +x setup.sh
          sudo ./setup.sh
      - name: build
        run: make build
      - name: clean
        run: make clean
      - name: run
        run: make run
      - name: post
        run: make post POST_NAME=Hi
      - name: help
        run: make help
      - name: package
        run: make package
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
            name: dist-without-markdown
            path: |
            dist
            !dist/**/*.md