---
name: module3_task1

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  container_test_job:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Install missing tools
        run: |
          cd module3_task1
          chmod +x setup.sh
          sudo ./setup.sh
      - name: build
        run: |
          cd module3_task1
          make build
      - name: clean
        run: make clean
      - name: run
        run: make run
      - name: post
        run: make post POST_NAME=Hi
      - name: help
        run: make help
      - name: package
        run: make package
