---
name: module3_task1

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main

jobs:
  container_test_job:
    runs-on: ubuntu-22.04
    container:
      image: ubuntu:22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install missing tools
        run: |
          cd module3_task1
          chmod +x setup.sh
          ./setup.sh
          cd ../module2_task3
          make build
          

