---
name: module3_task1

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  container_test_job:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Install missing tools
        run: |
          cd module3_task1
          chmod +x setup.sh
          ./setup.sh
          make build
          make clean
          make run
          make post POST_NAME=Hi
          make help
          

