---
name: module3_task2

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  container_test_job:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Install missing tools
        run: |
          cd module3_task2
          chmod +x setup.sh
          sudo ./setup.sh
      - name: build
        run: |
          cd module3_task2
          make build
      - name: clean
        run: |
          cd module3_task2 
          make clean
      - name: run
        run: |
          cd module3_task2 
          make run
      - name: help
        run: |
          cd module3_task2
          make help
      - name: package
        run: |
          cd module3_task2
          make package
      - name: Archive production artifacts
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: actions/upload-artifact@v3
        with:
            name: zip
            path: module3_task2/awesome-website.zip
